### ISSUE TITLE
What is the order in which the program runs? 

### ISSUE THREAD

**Issue by fc-smile2** [farismismar/Deep-Reinforcement-Learning-for-5G-Networks#1]
When I run the main program, only five txt files (measurement_220_seed47, measurement_23_seed188, measurement_220_seed337, measurement_716_seed348, optimal) are generated. Then when I run the plotting_v5 file, I will make an error (File NotFoundError: File's figures_M = 4/ue_1_sinr.txt'does not exist). How should I modify it? Or what is the order in which the program runs?

**Comment by farismismar** [comment]
Thanks for your comment.  I left a readme file describing how this runs.  Let me know if you have any further issues.
